package api;

/**
 * Created by WeedBreed on 12/09/2017.
 */
public class Items {
    public final String BEGINNERS_MERCENARY_JACKET = "T1_ARMOR_LEATHER_SET1";
    public final String NOVICES_MERCENARY_JACKET = "T2_ARMOR_LEATHER_SET1";
    public final String JOURNEYMANS_MERCENARY_JACKET = "T3_ARMOR_LEATHER_SET1";

    public final String ADEPTS_MERCENARY_JACKET1 = "T4_ARMOR_LEATHER_SET1";
    public final String ADEPTS_MERCENARY_JACKET2 = "T4_ARMOR_LEATHER_SET1@1";
    public final String ADEPTS_MERCENARY_JACKET3 = "T4_ARMOR_LEATHER_SET1@2";
    public final String ADEPTS_MERCENARY_JACKET4 = "T4_ARMOR_LEATHER_SET1@3";

    public final String EXPERTS_MERCENARY_JACKET1 = "T5_ARMOR_LEATHER_SET1";
    public final String EXPERTS_MERCENARY_JACKET2 = "T5_ARMOR_LEATHER_SET1@1";
    public final String EXPERTS_MERCENARY_JACKET3 = "T5_ARMOR_LEATHER_SET1@2";
    public final String EXPERTS_MERCENARY_JACKET4 = "T5_ARMOR_LEATHER_SET1@3";

    public final String MASTERS_MERCENARY_JACKET1 = "T6_ARMOR_LEATHER_SET1";
    public final String MASTERS_MERCENARY_JACKET2 = "T6_ARMOR_LEATHER_SET1@1";
    public final String MASTERS_MERCENARY_JACKET3 = "T6_ARMOR_LEATHER_SET1@2";
    public final String MASTERS_MERCENARY_JACKET4 = "T6_ARMOR_LEATHER_SET1@3";

    public final String GRANDMASTERS_MERCENARY_JACKET1 = "T7_ARMOR_LEATHER_SET1";
    public final String GRANDMASTERS_MERCENARY_JACKET2 = "T7_ARMOR_LEATHER_SET1@1";
    public final String GRANDMASTERS_MERCENARY_JACKET3 = "T7_ARMOR_LEATHER_SET1@2";
    public final String GRANDMASTERS_MERCENARY_JACKET4 = "T7_ARMOR_LEATHER_SET1@3";

    public final String ELDERS_MERCENARY_JACKET1 = "T8_ARMOR_LEATHER_SET1";
    public final String ELDERS_MERCENARY_JACKET2 = "T8_ARMOR_LEATHER_SET1@1";
    public final String ELDERS_MERCENARY_JACKET3 = "T8_ARMOR_LEATHER_SET1@2";
    public final String ELDERS_MERCENARY_JACKET4 = "T8_ARMOR_LEATHER_SET1@3";

    public final String EXPLORERS_ARMOR = "UNIQUE_ARMOR_FOUNDER_ELITE";
    public final String LEGENDARY_EXPLORERS_ARMOR = "UNIQUE_ARMOR_FOUNDER_LEGENDARY";

    public final String ADVENTURERS_JACKET = "UNIQUE_ARMOR_STARTERPACK_ELITE";

    public final String ADEPTS_HELLION_JACKET1 = "T4_ARMOR_LEATHER_HELL";
    public final String ADEPTS_HELLION_JACKET2 = "T4_ARMOR_LEATHER_HELL@1";
    public final String ADEPTS_HELLION_JACKET3 = "T4_ARMOR_LEATHER_HELL@2";
    public final String ADEPTS_HELLION_JACKET4 = "T4_ARMOR_LEATHER_HELL@3";

    public final String EXPERTS_HELLION_JACKET1 = "T5_ARMOR_LEATHER_HELL";
    public final String EXPERTS_HELLION_JACKET2 = "T5_ARMOR_LEATHER_HELL@1";
    public final String EXPERTS_HELLION_JACKET3 = "T5_ARMOR_LEATHER_HELL@2";
    public final String EXPERTS_HELLION_JACKET4 = "T5_ARMOR_LEATHER_HELL@3";

    public final String MASTERS_HELLION_JACKET1 = "T6_ARMOR_LEATHER_HELL";
    public final String MASTERS_HELLION_JACKET2 = "T6_ARMOR_LEATHER_HELL@1";
    public final String MASTERS_HELLION_JACKET3 = "T6_ARMOR_LEATHER_HELL@2";
    public final String MASTERS_HELLION_JACKET4 = "T6_ARMOR_LEATHER_HELL@3";

    public final String GRANDMASTERS_HELLION_JACKET1 = "T7_ARMOR_LEATHER_HELL";
    public final String GRANDMASTERS_HELLION_JACKET2 = "T7_ARMOR_LEATHER_HELL@1";
    public final String GRANDMASTERS_HELLION_JACKET3 = "T7_ARMOR_LEATHER_HELL@2";
    public final String GRANDMASTERS_HELLION_JACKET4 = "T7_ARMOR_LEATHER_HELL@3";

    public final String ELDERS_HELLION_JACKET1 = "T8_ARMOR_LEATHER_HELL";
    public final String ELDERS_HELLION_JACKET2 = "T8_ARMOR_LEATHER_HELL@1";
    public final String ELDERS_HELLION_JACKET3 = "T8_ARMOR_LEATHER_HELL@2";
    public final String ELDERS_HELLION_JACKET4 = "T8_ARMOR_LEATHER_HELL@3";

    public final String ADEPTS_HUNTER_JACKET1 = "T4_ARMOR_LEATHER_SET2";
    public final String ADEPTS_HUNTER_JACKET2 = "T4_ARMOR_LEATHER_SET2@1";
    public final String ADEPTS_HUNTER_JACKET3 = "T4_ARMOR_LEATHER_SET2@2";
    public final String ADEPTS_HUNTER_JACKET4 = "T4_ARMOR_LEATHER_SET2@3";

    public final String EXPERTS_HUNTER_JACKET1 = "T5_ARMOR_LEATHER_SET2";
    public final String EXPERTS_HUNTER_JACKET2 = "T5_ARMOR_LEATHER_SET2@1";
    public final String EXPERTS_HUNTER_JACKET3 = "T5_ARROR_LEATHER_SET2@2";
    public final String EXPERTS_HUNTER_JACKET4 = "T5_ARMOR_LEATHER_SET2@3";

    public final String MASTERS_HUNTER_JACKET1 = "T6_ARMOR_LEATHER_SET2";
    public final String MASTERS_HUNTER_JACKET2 = "T6_ARMOR_LEATHER_SET2@1";
    public final String MASTERS_HUNTER_JACKET3 = "T6_ARMOR_LEATHER_SET2@2";
    public final String MASTERS_HUNTER_JACKET4 = "T6_ARMOR_LEATHER_SET2@3";

    public final String GRANDMASTERS_HUNTER_JACKET1 = "T7_ARMOR_LEATHER_SET2";
    public final String GRNADMASTERS_HUNTER_JACKET2 = "T7_ARMOR_LEATHER_SET2@1";
    public final String GRANDMASTERS_HUNTER_JACKET3 = "T7_ARMOR_LEATHER_SET2@2";
    public final String GRANDMASTERS_HUNTER_JACKET4 = "T7_ARMOR_LEATHER_SET2@3";

    public final String ELDERS_HUNTER_JACKET1 = "T8_ARMOR_LEATHER_SET2";
    public final String ELDERS_HUNTER_JACKET2 = "T8_ARMOR_LEATHER_SET2@1";
    public final String ELDERS_HUNTER_JACKET3 = "T8_ARMOR_LEATHER_SET2@2";
    public final String ELDERS_HUNTER_JACKET4 = "T8_ARMOR_LEATHER_SET2@3";

    public final String ADEPTS_ASSASSIN_JACKET1 = "T4_ARMOR_LEATHER_SET3";
    public final String ADPETS_ASSASSIN_JACKET2 = "T4_ARMOR_LEATHER_SET3@1";
    public final String ADEPTS_ASSASSIN_JACKET3 = "T4_ARMOR_LEATHER_SET3@2";
    public final String ADEPTS_ASSASSIN_JACKET4 = "T4_ARMOR_LEATHER_SET3@3";

    public final String EXPERTS_ASSASSIN_JACKET1 = "T5_ARMOR_LEATHER_SET3";
    public final String EXPERTS_ASSASSIN_JACKET2 = "T5_ARMOR_LEATHER_SET3@1";
    public final String EXPERTS_ASSASSIN_JACKET3 = "T5_ARMOR_LEATHER_SET3@2";
    public final String EXPERTS_ASSASSIN_JACKET4 = "T5_ARMOR_LEATHER_SET3@3";

    public final String MASTERS_ASSASSIN_JACKET1 = "T6_ARMOR_LEATHER_SET3";
    public final String MASTERS_ASSASSIN_JACKET2 = "T6_ARMOR_LEATHER_SET3@1";
    public final String MASTERS_ASSASSIN_JACKET3 = "T6_ARMOR_LEATHER_SET3@2";
    public final String MASTERS_ASSASSIN_JACKET4 = "T6_ARMOR_LEATHER_SET3@3";

    public final String GRANDMASTERS_ASSASSIN_JACKET1 = "T7_ARMOR_LEATHER_SET3";
    public final String GRANDMASTERS_ASSASSIN_JACKET2 = "T7_ARMOR_LEATHER_SET3@1";
    public final String GRANDMASTERS_ASSASSIN_JACKET3 = "T7_ARMOR_LEATHER_SET3@2";
    public final String GRANDMASTERS_ASSASSIN_JACKET4 = "T7_ARMOR_LEATHER_SET3@3";

    public final String ELDERS_ASSASSIN_JACKET1 = "T8_ARMOR_LEATHER_SET3";
    public final String ELDERS_ASSASSIN_JACKET2 = "T8_ARMOR_LEATHER_SET3@1";
    public final String ELDERS_ASSASSIN_JACKET3 = "T8_ARMOR_LEATHER_SET3@2";
    public final String ELDERS_ASSASSIN_JACKET4 = "T8_ARMOR_LEATHER_SET3@3";

    public final String ADEPTS_STALKER_JACKET1 = "T4_ARMOR_LEATHER_MORGANA";
    public final String ADEPTS_STALKER_JACKET2 = "T4_ARMOR_LEATHER_MORGANA@1";
    public final String ADEPTS_STALKER_JACKET3 = "T4_ARMOR_LEATHER_MORGANA@2";
    public final String ADEPTS_STALKER_JACKET4 = "T4_ARMOR_LEATHER_MORGANA@3";

    public final String EXPERTS_STALKER_JACKET1 = "T5_ARMOR_LEATHER_MORGANA";
    public final String EXPERTS_STALKER_JACKET2 = "T5_ARMOR_LEATHER_MORGANA@1";
    public final String EXPERTS_STALKER_JACKET3 = "T5_ARMOR_LEATHER_MORGANA@2";
    public final String EXPERTS_STALKER_JACKET4 = "T5_ARMOR_LEATHER_MORGANA@3";

    public final String MASTERS_STALKER_JACKET1 = "T6_ARMOR_LEATHER_MORGANA";
    public final String MASTERS_STALKER_JACKET2 = "T6_ARMOR_LEATHER_MORGANA@1";
    public final String MASTERS_STALKER_JACKET3 = "T6_ARMOR_LEATHER_MORGANA@2";
    public final String MASTERS_STALKER_JACKET4 = "T6_ARMOR_LEATHER_MORGANA@3";

    public final String GRANDMASTERS_STALKER_JACKET1 = "T7_ARMOR_LEATHER_MORGANA";
    public final String GRANDMASTERS_STALKER_JACKET2 = "T7_ARMOR_LEATHER_MORGANA@1";
    public final String GRANDMASTERS_STALKER_JACKER3 = "T7_ARMOR_LEAHTER_MORGANA@2";
    public final String GRANDMASTERS_STALKER_JACKET4 = "T7_ARMOR_LEATHER_MORGANA@3";

    public final String ELDER_STALKER_JACKET1 = "T8_ARMOR_LEATHER_MORGANA";
    public final String ELDER_STALKER_JACKET2 = "T8_ARMOR_LEATHER_MORGANA@1";
    public final String ELDER_STALKER_JACKET3 = "T8_ARMOR_LEATHER_MORGANA@2";
    public final String ELDER_STALKER_JACKET4 = "T8_ARMOR_LEATHER_MORGANA@3";

    public final String ADEPTS_ROYAL_JACKET1 = "T4_ARMOR_LEATHER_ROYAL";
    public final String ADPETS_ROYAL_JACKET2 = "T4_ARMOR_LEATHER_ROYAL@1";
    public final String ADEPTS_ROYAL_JACKET3 = "T4_ARMOR_LEATHER_ROYAL@2";
    public final String ADEPTS_ROYAL_JACKET4 = "T4_ARMOR_LEATHER_ROYAL@3";

    public final String EXPERTS_ROYAL_JACKET1 = "T5_ARMOR_LEATHER_ROYAL";
    public final String EXPERTS_ROYAL_JACKET2 = "T5_ARMOR_LEATHER_ROYAL@1";
    public final String EXPERTS_ROYAL_JACKET3 = "T5_ARMOR_LEATHER_ROYAL@2";
    public final String EXPERTS_ROYAL_JACKET4 = "T5_ARMOR_LEATHER_ROYAL@3";

    public final String MASTERS_ROYAL_JACKET1 = "T6_ARMOR_LEATHER_ROYAL";
    public final String MASTERS_ROYAL_JACKET2 = "T6_ARMOR_LEATHER_ROYAL@1";
    public final String MASTERS_ROYAL_JACKET3 = "T6_ARMOR_LEATHER_ROYAL@2";
    public final String MASTERS_ROYAL_JACKET4 = "T6_ARMOR_LEATHER_ROYAL@3";

    public final String GRANDMASTERS_ROYAL_JACKET1 = "T7_ARMOR_LEATHER_ROYAL";
    public final String GRANDMASTERS_ROAYL_JACKET2 = "T7_ARMOR_LEATHER_ROYAL@1";
    public final String GRANDMASTERS_ROYAL_JACKET3 = "T7_ARMOR_LEATHER_ROYAL@2";
    public final String GRANDMASTERS_ROYAL_JACKET4 = "T7_ARMOR_LEATHER_ROYAL@3";

    public final String ELDER_ROYAL_JACKET1 = "T8_ARMOR_LEAHTER_ROYAL";
    public final String ELDER_ROYAL_JACKET2 = "T8_ARMOR_LEATHER_ROYAL@1";
    public final String ELDER_ROYAL_JACKET3 = "T8_ARMOR_LEATHER_ROYAL@2";
    public final String ELDER_ROYAL_JACKET4 = "T8_ARMOR_LEATHER_ROYAL@3";

    public final String BEGINNERS_MERCENARY_HOOD = "T1_HEAD_LEATHER_SET1";
    public final String NOVICES_MERCENARY_HOOD = "T2_HEAD_LEATHER_SET1";
    public final String JOURNEYMANS_MERCENARY_HOOD = "T3_HEAD_LEATHER_SET1";

    public final String ADEPTS_MERCENARY_HOOD1 = "T4_HEAD_LEATHER_SET1";
    public final String ADEPTS_MERCENARY_HOOD2 = "T4_HEAD_LEATHER_SET1@1";
    public final String ADEPTS_MERCENARY_HOOD3 = "T4_HEAD_LEATHER_SET1@2";
    public final String ADEPTS_MERCENARY_HOOD4 = "T4_HEAD_LEATHER_SET1@3";

    public final String EXPERTS_MERCENARY_HOOD1 = "T5_HEAD_LEATHER_SET1";
    public final String EXPERTS_MERCENARY_HOOD2 = "T5_HEAD_LEATHER_SET1@1";
    public final String EXPERTS_MERCENARY_HOOD3 = "T5_HEAD_LEATHER_SET1@2";
    public final String EXPERTS_MERCENARY_HOOD4 = "T5_HEAD_LEATHER_SET1@3";

    public final String MASTERS_MERCENARY_HOOD1 = "T6_HEAD_LEATHER_SET1";
    public final String MASTERS_MERCENARY_HOOD2 = "T6_HEAD_LEATHER_SET1@1";
    public final String MASTERS_MERCENARY_HOOD3 = "T6_HEAD_LEATHER_SET1@2";
    public final String MASTERS_MERCENARY_HOOD4 = "T6_HEAD_LEATHER_SET1@3";

    public final String GRANDMASTERS_MERCENARY_HOOD1 = "T7_HEAD_LEATHER_SET1";
    public final String GRANDMASTERS_MERCENARY_HOOD2 = "T7_HEAD_LEATHER_SET1@1";
    public final String GRANDMASTERS_MERCENARY_HOOD3 = "T7_HEAD_LEATHER_SET1@2";
    public final String GRANDMASTERS_MERCENARY_HOOD4 = "T7_HEAD_LEATHER_SET1@3";

    public final String ELDERS_MERCENARY_HOOD1 = "T8_HEAD_LEATHER_SET1";
    public final String ELDERS_MERCENARY_HOOD2 = "T8_HEAD_LEATHER_SET1@1";
    public final String ELDERS_MERCENARY_HOOD3 = "T8_HEAD_LEATHER_SET1@2";
    public final String ELDERS_MERCENARY_HOOD4 = "T8_HEAD_LEATHER_SET1@3";

    public final String EXPLORERS_HAT = "UNIQUE_HEAD_FOUNDER_ELITE";
    public final String ADVENTURERS_HELMET = "UNIQUE_HEAD_STARTERPACK_ELITE";
    public final String UNCLE_FROSTS_HAT = "UNIQUE_HEAD_XMAS";
    public final String LEGENDARY_EXPLORERS_HAT = "UNIQUE_HEAD_FOUNDER_LEGENDARY";

    public final String ADEPTS_HELLION_HOOD1 = "T4_HEAD_LEATHER_HELL";
    public final String ADEPTS_HELLION_HOOD2 = "T4_HEAD_LEATHER_HELL@1";
    public final String ADEPTS_HELLION_HOOD3 = "T4_HEAD_LEATHER_HELL@2";
    public final String ADEPTS_HELLION_HODD4 = "T4_HEAD_LEATHER_HELL@3";

    public final String EXPERTS_HELLION_HOOD1 = "T5_HEAD_LEATHER_HELL";
    public final String EXPERTS_HELLION_HOOD2 = "T5_HEAD_LEATHER_HELL@1";
    public final String EXPERTS_HELLION_HOOD3 = "T5_HEAD_LEATHER_HELL@2";
    public final String EXPERTS_HELLION_HOOD4 = "T5_HEAD_LEATHER_HELL@3";

    public final String MASTERS_HELLION_HOOD1 = "T6_HEAD_LEATHER_HELL";
    public final String MASTERS_HELLION_HOOD2 = "T6_HEAD_LEATHER_HELL@1";
    public final String MASTERS_HELLION_HOOD3 = "T6_HEAD_LEATHER_HELL@2";
    public final String MASTERS_HELLION_HOOD4 = "T6_HEAD_LEATHER_HELL@3";

    public final String GRANDMASTERS_HELLION_HOOD1 = "T7_HEAD_LEATHER_HELL";
    public final String GRANDMASTERS_HELLION_HOOD2 = "T7_HEAD_LEATHER_HELL@1";
    public final String GRANDMASTERS_HELLION_HOOD3 = "T7_HEAD_LEATHER_HELL@2";
    public final String GRANDMASTERS_HELLION_HOOD4 = "T7_HEAD_LEATHER_HELL@3";

    public final String ELDERS_HELLION_HOOD1 = "T8_HEAD_LEATHER_HELL";
    public final String ELDERS_HELLION_HOOD2 = "T8_HEAD_LEATHER_HELL@1";
    public final String ELDERS_HELLION_HOOD3 = "T8_HEAD_LEATHER_HELL@2";
    public final String ELDERS_HELLION_HOOD4 = "T8_HEAD_LEATHER_HELL@3";

    public final String ADEPTS_HUNTER_HOOD1 = "T4_HEAD_LEATHER_SET2";
    public final String ADEPTS_HUNTER_HOOD2 = "T4_HEAD_LEATHER_SET2@1";
    public final String ADEPTS_HUNTER_HOOD3 = "T4_HEAD_LEATHER_SET2@2";
    public final String ADPETS_HUNTER_HOOD4 = "T4_HEAD_LEATHER_SET2@3";

    public final String EXPERTS_HUNTER_HOOD1 = "T5_HEAD_LEATHER_SET2";
    public final String EXPERTS_HUNTER_HOOD2 = "T5_HEAD_LEATHER_SET2@1";
    public final String EXPERTS_HUNTER_HOOD3 = "T5_HEAD_LEATHER_SET2@2";
    public final String EXPERTS_HUNTER_HOOD4 = "T5_HEAD_LEATHER_SET2@3";

    public final String MASTERS_HUNTER_HOOD1 = "T6_HEAD_LEAHTER_SET2";
    public final String MASTERS_HUNTER_HOOD2 = "T6_HEAD_LEATHER_SET2@1";
    public final String MASTERS_HUNTER_HOOD3 = "T6_HEAD_LEATHER_SET2@2";
    public final String MASTERS_HUNTER_HOOD4 = "T6_HEAD_LEATHER_SET2@3";

    public final String GRANDMASTERS_HUNTER_HOOD1 = "T7_HEAD_LEATHER_SET2";
    public final String GRANDMASTERS_HUNTER_HOOD2 = "T7_HEAD_LEATHER_SET2@1";
    public final String GRANDMASTERS_HUNTER_HOOD3 = "T7_HEAD_LEATHER_SET2@2";
    public final String GRANDMASTERS_HUNTER_HOOD4 = "T7_HEAD_LEATHER_SET2@3";

    public final String ELDERS_HUNTER_HOOD1 = "T8_HEAD_LEATHER_SET2";
    public final String ELDERS_HUNTER_HOOD2 = "T8_HEAD_LEATHER_SET2@1";
    public final String ELDERS_HUNTER_HOOD3 = "T8_HEAD_LEATHER_SET2@2";
    public final String ELDERS_HUNTER_HOOD4 = "T8_HEAD_LEATHER_SET2@3";

    public final String ADEPTS_ASSASSIN_HOOD1 = "T4_HEAD_LEATHER_SET3";
    public final String ADEPTS_ASSASSIN_HOOD2 = "T4_HEAD_LEATEHR_SET3@1";
    public final String ADEPTS_ASSASSIN_HOOD3 = "T4_HEAD_LEATHER_SET3@2";
    public final String ADEPTS_ASSASSIN_HOOD4 = "T4_HEAD_LEATHER_SET3@3";

    public final String EXPERTS_ASSASSIN_HOOD1 = "T5_HEAD_LEATHER_SET3";
    public final String EXPERTS_ASSASSIN_HOOD2 = "T5_HEAD_LEATEHR_SET3@1";
    public final String EXPERTS_ASSASSIN_HOOD3 = "T5_HEAD_LEATHER_SET3@2";
    public final String EXPERTS_ASSASSIN_HOOD4 = "T5_HEAD_LEATHER_SET3@3";

    public final String MASTERS_ASSASSIN_HOOD1 = "T6_HEAD_LEATHER_SET3";
    public final String MASTERS_ASSASSIN_HOOD2 = "T6_HEAD_LEATHER_SET3@1";
    public final String MASTERS_ASSASSIN_HOOD3 = "T6_HEAD_LEATHER_SET3@2";
    public final String MASTERS_ASSASSIN_HOOD4 = "T6_HEAD_LEATHER_SET3@3";

    public final String GRANDMASTERS_ASSASSIN_HOOD1 = "T7_HEAD_LEATHER_SET3";
    public final String GRANDMASTERS_ASSASSIN_HOOD2 = "T7_HEAD_LEATHER_SET3@1";
    public final String GRANDMASTERS_ASSASSIN_HOOD3 = "T7_HEAD_LEATHER_SET3@2";
    public final String GRANDMASTERS_ASSASSIN_HOOD4 = "T7_HEAD_LEATHER_SET3@3";

    public final String ELDERS_ASSASSIN_HOOD1 = "T8_HEAD_LEATHER_SET3";
    public final String ELDERS_ASSASSIN_HOOD2 = "T8_HEAD_LEATHER_SET3@1";
    public final String ELDERS_ASSASSIN_HOOD3 = "T8_HEAD_LEATHER_SET3@2";
    public final String ELDERS_ASSASSIN_HOOD4 = "T8_HEAD_LEATHER_SET3@3";

    public final String ADEPTS_STALKER_HOOD1 = "T4_HEAD_LEATHER_MORGANA";
    public final String ADEPTS_STALKER_HOOD2 = "T4_HEAD_LEATHER_MORGANA@1";
    public final String ADEPTS_STALKER_HOOD3 = "T4_HEAD_LEATHER_MORGANA@2";
    public final String ADEPTS_STALKER_HOOD4 = "T4_HEAD_LEATHER_MORGANA@3";

    public final String EXPERTS_STALKER_HOOD1 = "T5_HEAD_LEATHER_MORGANA";
    public final String EXPERTS_STALKER_HOOD2 = "T5_HEAD_LEATHER_MORGANA@1";
    public final String EXPERTS_STALKER_HOOD3 = "T5_HEAD_LEATHER_MORGANA@2";
    public final String EXPERTS_STALKER_HOOD4 = "T5_HEAD_LEATHER_MORGANA@3";

    public final String MASTERS_STALKER_HOOD1 = "T6_HEAD_LEATHER_MORGANA";
    public final String MASTERS_STALKER_HOOD2 = "T6_HEAD_LEATHER_MORGANA@1";
    public final String MASTERS_STALKER_HOOD3 = "T6_HEAD_LEATHER_MORGANA@2";
    public final String MASTERS_STALKER_HOOD4 = "T6_HEAD_LEATHER_MORGANA@3";

    public final String GRANDMASTERS_STALKER_HOOD1 = "T7_HEAD_LEATHER_MORGANA";
    public final String GRANDMASTERS_STALKER_HOOD2 = "T7_HEAD_LEATHER_MORGANA@1";
    public final String GRANDMASTERS_STALKER_HOOD3 = "T7_HEAD_LEATHER_MORGANA@2";
    public final String GRANDMASTERS_STALKER_HOOD4 = "T7_HEAD_LEATHER_MORGANA@3";

    public final String ELDERS_STALKER_HOOD1 = "T8_HEAD_LEATHER_MORGANA";
    public final String ELDERS_STALKER_HOOD2 = "T8_HEAD_LEATHER_MORGANA@1";
    public final String ELDERS_STALKER_HOOD3 = "T8_HEAD_LEATHER_MORGANA@2";
    public final String ELDERS_STALKER_HOOD4 = "T8_HEAD_LEATHER_MORGANA@3";

    public final String ADEPTS_ROYAL_HOOD1 = "T4_HEAD_LEATHER_ROYAL";
    public final String ADEPTS_ROYAL_HOOD2 = "T4_HEAD_LEATHER_ROYAL@1";
    public final String ADEPTS_ROYAL_HOOD3 = "T4_HEAD_LEATHER_ROYAL@2";
    public final String ADEPTS_ROYAL_HOOD4 = "T4_HEAD_LEATHER_ROYAL@3";

    public final String EXPERTS_ROYAL_HOOD1 = "T5_HEAD_LEATHER_ROYAL";
    public final String EXPERTS_ROYAL_HOOD2 = "T5_HEAD_LEATEHR_ROYAL@1";
    public final String EXPERTS_ROYAL_HOOD3 = "T5_HEAD_LEATHER_ROYAL@2";
    public final String EXPERTS_ROYAL_HOOD4 = "T5_HEAD_LEATHER_ROYAL@3";

    public final String MASTERS_ROYAL_HOOD1 = "T6_HEAD_LEATHER_ROYAL";
    public final String MASTERS_ROYAL_HOOD2 = "T6_HEAD_LEATHER_ROYAL@1";
    public final String MASTERS_ROYAL_HOOD3 = "T6_HEAD_LEATHER_ROYAL@2";
    public final String MASTERS_ROYAL_HOOD4 = "T6_HEAD_LEATHER_ROYAL@3";

    public final String GRANDMASTERS_ROYAL_HOOD1 = "T7_HEAD_LEATHER_ROYAL";
    public final String GRANDMASTERS_ROYAL_HOOD2 = "T7_HEAD_LEATHER_ROYAL@1";
    public final String GRANDMASTERS_ROYAL_HOOD3 = "T7_HEAD_LEATHER_ROYAL@2";
    public final String GRANDMASTERS_ROYAL_HOOD4 = "T7_HEAD_LEATHER_ROYAL@3";

    public final String ELDERS_ROYAL_HOOD1 = "T8_HEAD_LEATHER_ROYAL";
    public final String ELDERS_ROYAL_HOOD2 = "T8_HEAD_LEATHER_ROYAL@1";
    public final String ELDERS_ROYAL_HOOD3 = "T8_HEAD_LEATHER_ROYAL@2";
    public final String ELDERS_ROYAL_HOOD4 = "T8_HEAD_LEATHER_ROYAL@3";

    
}
