package api.leather.shoes;

/**
 * Created by WeedBreed on 14/09/2017.
 */
public class LeatherShoeItems {
    /** Basic Shoes */
    public final String BEGINNERS_MERCENARY_SHOES = "T1_SHOES_LEATHER_SET1";
    public final String NOVICES_MERCENARY_SHOES = "T2_SHOES_LEATHER_SET1";
    public final String EXPLORERS_BOOTS = "UNIQUE_SHOES_FOUNDER_ELITE";
    public final String ADVENTURERS_SHOES = "UNIQUE_SHOES_STARTERPACK_ELITE";
    public final String JOURNEYMANS_MERCENARY_SHOES = "T3_SHOES_LEATHER_SET1";
    public final String LEGENDARY_EXPLORERS_BOOTS = "UNIQUE_SHOES_FOUNDER_LEGENDARY";

    /** T4 Hellion Shoes */
    public final String ADEPTS_HELLION_SHOES1 = "T4_SHOES_LEATHER_HELL";
    public final String ADEPTS_HELLION_SHOES2 = "T4_SHOES_LEATHER_HELL@1";
    public final String ADEPTS_HELLION_SHOES3 = "T4_SHOES_LEATHER_HELL@2";
    public final String ADEPTS_HELLION_SHOES4 = "T4_SHOES_LEATHER_HELL@3";

    /** T5 Hellion Shoes */
    public final String EXPERTS_HELLION_SHOES1 = "T5_SHOES_LEATHER_HELL";
    public final String EXPERTS_HELLION_SHOES2 = "T5_SHOES_LEATHER_HELL@1";
    public final String EXPERTS_HELLION_SHOES3 = "T5_SHOES_LEATHER_HELL@2";
    public final String EXPERTS_HELLION_SHOES4 = "T5_SHOES_LEATHER_HELL@3";

    /** T6 Hellion Shoes */
    public final String MASTERS_HELLION_SHOES1 = "T6_SHOES_LEATHER_HELL";
    public final String MASTERS_HELLION_SHOES2 = "T6_SHOES_LEATHER_HELL@1";
    public final String MASTERS_HELLION_SHOES3 = "T6_SHOES_LEATHER_HELL@2";
    public final String MASTERS_HELLION_SHOES4 = "T6_SHOES_LEATHER_HELL@3";

    /** T7 Hellion Shoes */
    public final String GRANDMASTERS_HELLION_SHOES1 = "T7_SHOES_LEATHER_HELL";
    public final String GRANDMASTERS_HELLION_SHOES2 = "T7_SHOES_LEATHER_HELL@1";
    public final String GRANDMASTERS_HELLION_SHOES3 = "T7_SHOES_LEATHER_HELL@2";
    public final String GRANDMASTERS_HELLION_SHOES4 = "T7_SHOES_LEATHER_HELL@3";

    /** T8 Hellion Shoes */
    public final String ELDERS_HELLION_SHOES1 = "T8_SHOES_LEATHER_HELL";
    public final String ELDERS_HELLION_SHOES2 = "T8_SHOES_LEATHER_HELL@1";
    public final String ELDERS_HELLION_SHOES3 = "T8_SHOES_LEATHER_HELL@2";
    public final String ELDERS_HELLION_SHOES4 = "T8_SHOES_LEATHER_HELL@3";

    /** T4 Mercenary Shoes */
    public final String ADEPTS_MERCENARY_SHOES1 = "T4_SHOES_LEATHER_SET1";
    public final String ADEPTS_MERCENARY_SHOES2 = "T4_SHOES_LEATHER_SET1@1";
    public final String ADPETS_MERCENARY_SHOES3 = "T4_SHOES_LEATHER_SET1@2";
    public final String ADEPTS_MERCENARY_SHOES4 = "T4_SHOES_LEATHER_SET1@3";

    /** T5 Mercenary Shoes */
    public final String EXPERTS_MERCENARY_SHOES1 = "T5_SHOES_LEATHER_SET1";
    public final String EXPERTS_MERCENARY_SHOES2 = "T5_SHOES_LEATHER_SET1@1";
    public final String EXPERTS_MERCENARY_SHOES3 = "T5_SHOES_LEATHER_SET1@2";
    public final String EXPERTS_MERCENARY_SHOES4 = "T5_SHOES_LEATHER_SET1@3";

    /** T6 Mercenary Shoes */
    public final String MASTERS_MERCENARY_SHOES1 = "T6_SHOES_LEATHER_SET1";
    public final String MASTERS_MERCENARY_SHOES2 = "T6_SHOES_LEATHER_SET1@1";
    public final String MASTERS_MERCENARY_SHOES3 = "T6_SHOES_LEATHER_SET1@2";
    public final String MASTERS_MERCENARY_SHOES4 = "T6_SHOES_LEATHER_SET1@3";

    /** T7 Mercenary Shoes */
    public final String GRANDMASTERS_MERCENARY_SHOES1 = "T7_SHOES_LEATHER_SET1";
    public final String GRANDMASTERS_MERCENARY_SHOES2 = "T7_SHOES_LEATHER_SET1@1";
    public final String GRANDMASTERS_MERCENARY_SHOES3 = "T7_SHOES_LEATHER_SET1@2";
    public final String GRANDMASTERS_MERCENARY_SHOES4 = "T7_SHOES_LEATHER_SET1@3";

    /** T8 Mercenary Shoes */
    public final String ELDERS_MERCENARY_SHOES1 = "T8_SHOES_LEATHER_SET1";
    public final String ELDERS_MERCENARY_SHOES2 = "T8_SHOES_LEATHER_SET1@1";
    public final String ELDERS_MERCENARY_SHOES3 = "T8_SHOES_LEATHER_SET1@2";
    public final String ELDERS_MERCENARY_SHOES4 = "T8_SHOES_LEATHER_SET1@3";

    /** T4 Hunter Shoes */
    public final String ADEPTS_HUNTER_SHOES1 = "T4_SHOES_LEATHER_SET2";
    public final String ADPETS_HUNTER_SHOES2 = "T4_SHOES_LEATHER_SET2@1";
    public final String ADEPTS_HUNTER_SHOES3 = "T4_SHOES_LEATHER_SET@2";
    public final String ADPETS_HUNTER_SHOES4 = "T4_SHOES_LEATHER_SET2@3";

    /** T5 Hunter Shoes */
    public final String EXPERTS_HUNTER_SHOES1 = "T5_SHOES_LEATHER_SET2";
    public final String EXPERTS_HUNTER_SHOES2 = "T5_SHOES_LEATHER_SET2@1";
    public final String EXPERTS_HUNTER_SHOES3 = "T5_SHOES_LEATHER_SET2@2";
    public final String EXPERTS_HUNTER_SHOES4 = "T5_SHOES_LEATHER_SET2@3";

    /** T6 Hunter Shoes */
    public final String MASTERS_HUNTER_SHOES1 = "T6_SHOES_LEATHER_SET2";
    public final String MASTERS_HUNTER_SHOES2 = "T6_SHOES_LEATHER_SET2@1";
    public final String MASTERS_HUNTER_SHOES3 = "T6_SHOES_LEATHER_SET2@2";
    public final String MASTERS_HUNTER_SHOES4 = "T6_SHOES_LEATHER_SET2@3";

    /** T7 Hunter Shoes */
    public final String GRANDMASTERS_HUNTER_SHOES1 = "T7_SHOES_LEATHER_SET2";
    public final String GRANDMASTERS_HUNTER_SHOES2 = "T7_SHOES_LEATHER_SET2@1";
    public final String GRANDMASTERS_HUNTER_SHOES3 = "T7_SHOES_LEATHER_SET2@2";
    public final String GRANDMASTERS_HUNTER_SHOES4 = "T7_SHOES_LEATHER_SET2@3";

    /** T8 Hunter Shoes */
    public final String ELDERS_HUNTER_SHOES1 = "T8_SHOES_LEATHER_SET2";
    public final String ELDERS_HUNTER_SHOES2 = "T8_SHOES_LEATHER_SET2@1";
    public final String ELDERS_HUNTER_SHOES3 = "T8_SHOES_LEATHER_SET2@2";
    public final String ELDERS_HUNTER_SHOES4 = "T8_SHOES_LEATHER_SET2@3";

    public final String ADEPTS_ASSASSIN_SHOES1 = "T4_SHOES_LEATHER_SET3";
    public final String ADEPTS_ASSASSIN_SHOES2 = "T4_SHOES_LEATHER_SET3@1";
    public final String ADEPTS_ASSASSIN_SHOES3 = "T4_SHOES_LEATHER_SET3@2";
    public final String ADEPTS_ASSASSIN_SHOES4 = "T4_SHOES_LEATHER_SET3@3";

    public final String EXPERTS_ASSASSIN_SHOES1 = "T5_SHOES_LEATHER_SET3";
    public final String EXPERTS_ASSASSIN_SHOES2 = "T5_SHOES_LEATHER_SET3@1";
    public final String EXPERTS_ASSASSIN_SHOES3 = "T5_SHOES_LEATHER_SET3@2";
    public final String EXPERTS_ASSASSIN_SHOES4 = "T5_SHOES_LEATHER_SET3@3";

    public final String MASTERS_ASSASSIN_SHOES1 = "T6_SHOES_LEATHER_SET3";
    public final String MASTERS_ASSASSIN_SHOES2 = "T6_SHOES_LEATHER_SET3@1";
    public final String MASTERS_ASSASSIN_SHOES3 = "T6_SHOES_LEATHER_SET3@2";
    public final String MASTERS_ASSASSIN_SHOES4 = "T6_SHOES_LEATHER_SET3@3";

    public final String GRANDMASTERS_ASSASSIN_SHOES1 = "T7_SHOES_LEATHER_SET3";
    public final String GRANDMASTERS_ASSASSIN_SHOES2 = "T7_SHOES_LEATHER_SET3@1";
    public final String GRANDMASTERS_ASSASSIN_SHOES3 = "T7_SHOES_LEATHER_SET3@2";
    public final String GRANDMASTERS_ASSASSIN_SHOES4 = "T7_SHOES_LEATEHR_SET3@3";

    public final String ELDERS_ASSASSIN_SHOES1 = "T8_SHOES_LEATHER_SET3";
    public final String ELDERS_ASSASSIN_SHOES2 = "T8_SHOES_LEATHER_SET3@1";
    public final String ELDERS_ASSASSIN_SHOES3 = "T8_SHOES_LEATHER_SET3@2";
    public final String ELDERS_ASSASSIN_SHOES4 = "T8_SHOES_LEATHER_SET3@3";

    public final String ADEPTS_STALKER_SHOES1 = "T4_SHOES_LEATHER_MORGANA";
    public final String ADEPTS_STALKER_SHOES2 = "T4_SHOES_LEATHER_MORGANA@1";
    public final String ADEPTS_STALKER_SHOES3 = "T4_SHOES_LEATHER_MORGANA@2";
    public final String ADEPTS_STALKER_SHOES4 = "T4_SHOES_LEATHER_MORGANA@3";

    public final String EXPERTS_STALKER_SHOES1 = "T5_SHOES_LEATHER_MORGANA";
    public final String EXPERTS_STALKER_SHOES2 = "T5_SHOES_LEATHER_MORGANA@1";
    public final String EXPERTS_STALKER_SHOES3 = "T5_SHOES_LEATHER_MORGANA@2";
    public final String EXPERTS_STALKER_SHOES4 = "T5_SHEOS_LEATHER_MORGANA@3";

    public final String MASTERS_STALKER_SHOES1 = "T6_SHOES_LEATHER_MORGANA";
    public final String MASTERS_STALKER_SHOES2 = "T6_SHOES_LEATHER_MORGANA@1";
    public final String MASTERS_STALKER_SHOES3 = "T6_SHOES_LEATHER_MORGANA@2";
    public final String MASTERS_STALKER_SHOES4 = "T6_SHOES_LEATHER_MORGANA@3";

    public final String GRANDMASTERS_STALKER_SHOES1 = "T7_SHOES_LEATHER_MORGANA";
    public final String GRANDMASTERS_STALKER_SHOES2 = "T7_SHOES_LEATHER_MORGANA@1";
    public final String GRANDMASTERS_STALKER_SHOES3 = "T7_SHOES_LEATHER_MORGANA@2";
    public final String GRANDMASTERS_STALKER_SHOES4 = "T7_SHOES_LEATHER_MORGANA@3";

    public final String ELDERS_STALKER_SHOES1 = "T8_SHOES_LEATHER_MORGANA";
    public final String ELDERS_STALKER_SHOES2 = "T8_SHOES_LEATHER_MORGANA@1";
    public final String ELDERS_STALKER_SHOES3 = "T8_SHOES_LEATHER_MORGANA@2";
    public final String ELDERS_STALKER_SHOES4 = "T8_SHOES_LEATHER_MORGANA@3";

    public final String ADEPTS_ROYAL_SHOES1 = "T4_SHOES_LEATHER_ROYAL";
    public final String ADEPTS_ROYAL_SHOES2 = "T4_SHOES_LEATHER_ROYAL@1";
    public final String ADEPTS_ROYAL_SHOES3 = "T4_SHOES_LEATHER_ROYAL@2";
    public final String ADEPTS_ROYAL_SHOES4 = "T4_SHOES_LEATHER_ROYAL@3";

    public final String EXPERTS_ROYAL_SHOES1 = "T5_SHOES_LEATHER_ROYAL";
    public final String EXPERTS_ROYAL_SHOES2 = "T5_SHOES_LEATHER_ROYAL@1";
    public final String EXPERTS_ROYAL_SHOES3 = "T5_SHOES_LEATHER_ROYAL@2";
    public final String EXPERTS_ROYAL_SHOES4 = "T5_SHOES_LEATHER_ROYAL@3";

    public final String MASTERS_ROYAL_SHOES1 = "T6_SHOES_LEATHER_ROYAL";
    public final String MASTERS_ROYAL_SHOES2 = "T6_SHOES_LEATHER_ROYAL@1";
    public final String MASTERS_ROYAL_SHOES3 = "T6_SHOES_LEATHER_ROYAL@2";
    public final String MASTERS_ROYAL_SHOES4 = "T6_SHOES_LEATHER_ROYAL@3";

    public final String GRANDMASTERS_ROYAL_SHOES1 = "T7_SHOES_LEATHER_ROYAL";
    public final String GRANDMASTERS_ROYAL_SHOES2 = "T7_SHOES_LEATHER_ROYAL@1";
    public final String GRANDMASTERS_ROYAL_SHOES3 = "T7_SHOES_LEATHER_ROYAL@2";
    public final String GRANDMASTERS_ROYAL_SHOES4 = "T7_SHOES_LEATHER_ROYAL@3";

    public final String ELDERS_ROYAL_SHOES1 = "T8_SHOES_LEATHER_ROYAL";
    public final String ELDERS_ROYAL_SHOES2 = "T8_SHOES_LEATHER_ROYAL@1";
    public final String ELDERS_ROYAL_SHOES3 = "T8_SHOES_LEATHER_ROYAL@2";
    public final String ELDERS_ROYAL_SHOES4 = "T8_SHOES_LEATHER_ROYAL@3";
}
